### PR TITLE
[Draft] Code Fix: C# 8 null coalescing assignment

### LINKED ISSUE #70: C# 8 null coalescing assignment
#### Problem statement
C# 8 introduces the `??=` operator, which is not going to work with `UnityObject`.

#### Proposed solution
Just like `??`, we should make sure Visual Studio doesn't offer to use that operator.

### PR DESCRIPTION
**Pull request by shreyalpandit**
Fixes #70 

#### Changes proposed in this pull request:

-Checks for "??=" operator and replaces it

### CODE REVIEW

**Comment by sailro** [comment]
Thanks for the PR!

Before addressing the technical details, I think something is missing in the design.

Indeed I think we have to keep separating the diagnostic/suppressors rules.

Reusing the existing infrastructure and testing against `SyntaxKind.CoalesceAssignmentExpression` is the good way to go though. But something is missing. 

I think we want to add a new rule to `UnityObjectNullHandlingAnalyzer` dedicated to _coalesce compound assignment_ which is distinct from the _coalesce expression_. That's why we have to distinct diagnostics `IDE0074` and `IDE0029`.

As a result we want to add a new rule to `UnityObjectNullHandlingSuppressor` to handle specifically `IDE0074`. Here I can see that we are testing against an already existing rule `IDE0029`. We're mixing distinct stuff.

So having something able to handle tests like this:

```csharp
		[Fact]
		public async Task CoalesceAssignmentSuppressed()
		{
			const string test = @"
using UnityEngine;

class Camera : MonoBehaviour
{
    public Transform a = null;
    public Transform b = null;

    public Transform NP()
    {
        return a ?? (a = b);
    }
}
";

			var suppressor = ExpectSuppressor(UnityObjectNullHandlingSuppressor.CoalesceAssignmentRule)
				.WithLocation(11, 18);

			await VerifyCSharpDiagnosticAsync(test, suppressor);
		}
```

where

```csharp
		internal static readonly SuppressionDescriptor CoalesceAssignmentRule = new SuppressionDescriptor(
			id: "USP00XX",
			suppressedDiagnosticId: "IDE0074",
			justification: Strings.UnityObjectCoalesceAssignmentSuppressorJustification);
```

and 

```csharp
		[Fact]
		public async Task DetectCoalesceAssignment()
		{
			const string test = @"
using UnityEngine;

class Camera : MonoBehaviour
{
    public Transform a = null;
    public Transform b = null;

    public Transform NP()
    {
        return a ??= b;
    }
}
";

			var diagnostic = ExpectDiagnostic(UnityObjectNullHandlingAnalyzer.CoalesceAssignmentRule)
				.WithLocation(11, 16);

			await VerifyCSharpDiagnosticAsync(test, diagnostic);

                        // ++ codefixes test if we want a code fix
		}

		[Fact]
		public async Task CoalesceAssignmentForRegularObjects()
		{
			const string test = @"
using UnityEngine;

class Camera : MonoBehaviour
{
    public System.Object a = null;
    public System.Object b = null;

    public System.Object NP()
    {
        return a ??= b;
    }
}
";

			await VerifyCSharpDiagnosticAsync(test); // we want regular objects to be able to use this construct
		}
```

where

```csharp
		internal static readonly DiagnosticDescriptor CoalesceAssignmentRule = new DiagnosticDescriptor(
			id: "UNT00XX",
			title: Strings.UnityObjectCoalesceAssignmentDiagnosticTitle,
			messageFormat: Strings.UnityObjectCoalesceAssignmentDiagnosticMessageFormat,
			category: DiagnosticCategory.Correctness,
			defaultSeverity: DiagnosticSeverity.Info,
			isEnabledByDefault: true,
			description: Strings.UnityObjectCoalesceAssignmentDiagnosticDescription);
```

What do you think?

**Comment by sailro** [comment]
See a prototype I made here:

https://github.com/microsoft/Microsoft.Unity.Analyzers/tree/coalescing-assignment

I think we just need to plug your codefix and extra tests in this one

**Comment by shreyalpandit** [comment]
Yes, I wasn't sure if a new one needed to be created since it was using the same pattern. But that makes sense for the test case with return a ?? (a = b);
Can a user return a??=b even though this is an assignment?

**Comment by sailro** [comment]
> Yes, I wasn't sure if a new one needed to be created since it was using the same pattern. But that makes sense for the test case with return a ?? (a = b);
> Can a user return a??=b even though this is an assignment?

yes that's because assignment expressions are passing the assigned value.

That's why we can do something like this:

```csharp
while ((var line = streamReader.ReadLine()) != null) {
   // do stuff with line
}
```

In my test I agree it is a bit strange, but this is only a trick to trigger the proper diagnostic.

**Comment by shreyalpandit** [comment]
Should a ?? (a = b) trigger IDE0074?

**Comment by sailro** [comment]
> Should a ?? (a = b) trigger IDE0074?

Yes.

**Comment by sailro** [comment]
> > Should a ?? (a = b) trigger IDE0074?
> 
> Yes.

@shreyalpandit, see what I did in:
https://github.com/microsoft/Microsoft.Unity.Analyzers/compare/coalescing-assignment

You'll need to toggle dotnet_style_prefer_compound_assignment

**Comment by shreyalpandit** [comment]
> > > Should a ?? (a = b) trigger IDE0074?
> > 
> > 
> > Yes.
> 
> @shreyalpandit, see what I did in:
> https://github.com/microsoft/Microsoft.Unity.Analyzers/compare/coalescing-assignment
> 
> You'll need to toggle dotnet_style_prefer_compound_assignment

Yes, I did that but am getting an exception still

**Comment by sailro** [comment]
Closing, as we'll integrate changes in https://github.com/microsoft/Microsoft.Unity.Analyzers/pull/143

**Pull request closed without merging**
