### PR TITLE
Add USP0022, UnityObjectIfNullCoalescingSuppressor

### LINKED ISSUE #323: IDE0270 should be suppressed by the UnityObjectNullHandlingAnalyzer
#### Problem statement
UnityObjectNullHandlingAnalyzer now supresses IDE0029 but not IDE0270. This causes IDE0270 to suggest null coalesce on Unity objects.
The following code example raises IDE0270
```
using UnityEngine;

class Camera : MonoBehaviour
{
	public void M()
	{
		Camera item = FindItem() as Camera;
		if (item == null)
			throw new System.InvalidOperationException();
	}

	MonoBehaviour FindItem() => null;
}
```

#### Proposed solution
Add IDE0270 as a supressor to the UnityObjectNullHandlingAnalyzer

### PR DESCRIPTION
**Pull request by JorisCleVR**
Fixes #323

#### Checklist

- [x] I have read the [Contribution Guide](/CONTRIBUTING.md) ;
- [x] There is an approved issue describing the change when contributing a new analyzer or suppressor ;
- [x] I have added tests that prove my fix is effective or that my feature works ;
- [x] I have added necessary documentation (if appropriate) ;

#### Short description of what this resolves:
- IDE0270 is suppressed by the UnityObjectNullHandlingAnalyzer

#### Changes proposed in this pull request:

- UnityObjectNullHandlingAnalyzer now supresses IDE0270

### CODE REVIEW

**Comment by JorisCleVR** [comment]
@microsoft-github-policy-service agree company="CleVR"

**Review by sailro — APPROVED** [review]
LGTM

**Comment by sailro** [comment]
Thank you @JorisCleVR for this contribution. Perfect !

**Comment by JorisCleVR** [comment]
Your welcome. Thank you for the fast integration

**Pull request merged**
